#如果不知道自己在干什么请别动着两行
ip: 127.0.0.1
port: 5555

admins: ['']

command_prefix: "/"

menu_key: ["菜单", "help", "cd"]
main_menu: "-----XYBot菜单------\n实用功能⚙️\n1.1 获取天气\n1.2 获取新闻\n1.3 ChatGPT\n\n娱乐功能🔥\n2.1 随机图图\n\n积分功能💰\n3.1 签到\n3.2 查询积分\n3.3 积分榜\n\n帮助指令格式/菜单 (编号)\n例如/菜单 1.1\n指令参数的()不用打"

menus: {"1.1": "-----XYBot菜单------\n1.1: 获取最新实时天气🌧️\n指令：/获取天气 (城市)\n⚠️注意只支持国内城市",
        "1.2": "-----XYBot菜单------\n1.2: 获取最新头条新闻📰\n指令: /新闻",
        "1.3": "-----XYBot菜单------\n1.3: 在微信中用ChatGPT🤖️\n(支持私聊)\n指令：/gpt (问题)\n⚠️注意！扣除3点积分！⚠️",
        "2.1": "-----XYBot菜单------\n2.1: 随机一个二次元图片！\n指令：/随机图图",
        "3.1": "-----XYBot菜单------\n3.1: 签到领取积分\n⚠️每天只能领取一次(每天3点刷新)\n指令：/签到",
        "3.2": "-----XYBot菜单------\n3.2: 查询自己的积分！\n指令：/查询积分",
        "3.3": "-----XYBot菜单------\n3.3: 查看积分排行榜！\n指令：/积分榜"}

random_pic_key: ["随机图图"]
random_pic_url: "https://dev.iw233.cn/wbapi.php?sort=random"

# 商业转载请联系作者获得授权，非商业转载请注明出处。
# For commercial use, please contact the author for authorization. For non-commercial use, please indicate the source.
# 协议(License)：署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)
# 作者(Author)：730716745
# 链接(URL)：https://blog.anosu.top/archives/22
# 来源(Source)：Anosu
random_pic_link_key: ["随机链接"]
#设置数量？看到链接最后面那个数字没？改它！
random_pic_link_url: "https://moe.jitsu.top/img/?type=json&num=3"

signin_key: ["签到"]
query_points_key: ["查询积分", "积分查询"]
points_leaderboard_key: ["积分榜", "积分排行榜"]

#ChatGPT的API网址
openai_api_base: ""
#ChatGPT API的Key
openai_api_key: ""
gpt_key: ["gpt", "chatgpt", "GPT", "ChatGPT", "CHATGPT"]
gpt_version: 'gpt-3.5-turbo'
gpt_point_price: 3

#请去 https://www.yiketianqi.com/ 申请API密钥
weather_key: ["天气", "获取天气"]
weather_api: "https://v0.yiketianqi.com/free/day"
weather_appid: ""
weather_appsecret: ""

#可更改 参考：https://blog.csdn.net/qq_41212530/article/details/85693158
news_key: ["新闻", "news", "new", "获取新闻"]
news_urls: ["http://c.m.163.com/nc/article/headline/T1348647853363/0-20.html", "https://c.m.163.com/nc/article/headline/T1348649580692/0-20.html", "http://c.3g.163.com/nc/article/list/T1348648517839/0-20.html"]
news_number: 3

admin_whitelist: ["管理白名单"]
admin_points: ["管理积分"]
admin_signin_reset: ["重置签到状态", "重置签到", "重置签到数据库"]