#Version 0.0.5
bot_version: "v0.0.5"

#如果不知道自己在干什么请别动这两行
ip: 127.0.0.1
port: 5555

admins: [ "" ]

max_worker: 25

command_prefix: "/" #如果需要前缀，则必须为一个字符  如果不需要前缀可设置为空，即 ""

excluded_plugins: [ "" ]

timezone: "Asia/Shanghai"
